dist: trusty
sudo: false
language: java
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh"
script: "${PWD}/target/travis-settings/java/script-install.sh"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"